### PR TITLE
Extend behaviour for Maven classifiers and types

### PR DESCRIPTION
**Pull request by gemelen**
Proposed changeset adds new behaviour in corner cases related to test artifacts for dependent modules.
Mostly it covers `test-jar` case more extensively than in previous attempts and translates such occurrences into Ivy's "test->test" configuration of module.

Also, tests are provided to illustrate a bug and a successful solution (to some degree).
Minimalist test Maven project is based on Maven-side of Apache Spark build file.

Seems to cover #38 #37 and reiterates an idea from PR #14 

Please review and comment, it'd be very nice to add this to plugin and replace Spark's fork with upstream (which is my current goal).

### CODE REVIEW

**Comment by gemelen** [comment]
Travis build is a bit outdated and slightly dead :)

**Comment by gemelen** [comment]
Trying direct mention, sorry for that: @dwijnand @metasim

**Comment by gemelen** [comment]
Awesome.
If I could help with build please let me know, I'd be glad to to offload effort from you.

**Comment by dongjoon-hyun** [comment]
Hi, All. Travis CI seems to be not happy for some other reasons still. Is there any update?

**Comment by gemelen** [comment]
I guess because CI script tries to setup JDK6 and fails, since it's not supported anymore.

**Comment by lightbend-cla-validator** [comment]
Hi @gemelen,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Pull request merged**
